---
driver_plugin: vagrant

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
- name: centos-6.6
  run_list:
  - recipe[yum-epel]
- name: sles-11sp3
  driver_config:
    box: opscode-sles-11sp3
  run_list:
  - recipe[zypper::smt_client]
  attributes:
    zypper:
      smt_host: <%= ENV['SMT_HOST'] %>

suites:
- name: data-bag-test
  run_list:
  - recipe[bind]
  - recipe[bind::databag]
  attributes: {
    "bind": {
      "databag": "test"
    }
  }
- name: default
  run_list:
  - recipe[bind_test]
  attributes: {}
