---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0 
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list: 
  - recipe[bind]
  attributes: {
    "databag": {
      "domains": "test"
    }
  }
